
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center indigo-text text-lighten-2">Contact form</h1>
        <div class="row center">
          <h5 class="header col s12 indigo-text">A modern responsive framework based on PHP</h5>
        </div>
        <div class="row center">
          <a href="<?php echo APP_URL; ?>" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Go Home</a>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="<?php echo RESOURCES; ?>/img/background4.jpg" alt="Unsplashed background img"></div>
  </div>


<div class="container">
    <h3 class="indigo-text center"></h3>
    <div class="row">
        <form class="col s12" method="POST" action="<?php echo APP_URL ?>/contact/email">

        <div class="row">
            <div class="input-field col s6">
                <input placeholder="Full Name" id="name" type="text" class="validate" name="full_name">
                <label for="name">Name</label>
            </div>
            <div class="input-field col s6">
                <input id="email" type="email" class="validate" name="email_address">
                <label for="email">Email</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <textarea id="message" class="materialize-textarea" name="text_message"></textarea>
                <label for="message">Message</label>
            </div>
        </div>      
        <div class="row">
            <div class="input-field col s4 offset-s4 center">
                <button class="btn waves-effect waves-light" type="submit" name="send">Submit
                    <i class="material-icons right">send</i>
                </button>
            </div>
        </div>  
        </form>
        <?php 
          if ($_COOKIE){
            if ($_COOKIE['SENT_MAIL']==true){
              ?>            
        <div class="collection">
          <div class="collection-item teal accent-4 white-text">
            <p class="center">Mensaje enviado</p>
          </div>
        </div>          
        <?php
            }
        }
        ?>

    </div>
</div>